gisce/switching

switching/data/Facturacion.xsd, switching/data/TiposComplejos.xsd, switching/data/TiposSencillos.xsd, switching/input/messages/F1.py, switching/output/messages/facturacio.py
* New XSD's with IndicativoCurvaCarga and PeriodoCCH
**OUTPUT**
* New PeriodoCCH model to enable tag generation
**INPUT**
* New funcion info_curva_carga to get CCH information if available
related to gisce/erp#2137
=> IMP F1 specs from new CNMC 6203

switching/input/messages/F1.py
Bad F1 PeriodoCCH reading
related to gisce/erp#2137
=> FIX PeriodoCCH reading

switching/data/RechazoAportacionLectura.xsd, switching/input/messages/W1.py, switching/input/messages/message.py, switching/output/messages/sw_w1.py, tests/data/w101.xml, tests/data/w102-aceptacio.xml, tests/data/w102-rebuig.xml, tests/test_switching.py
Read and write W1 switching process with testing
=> NEW W1 Full implementation

switching/output/messages/sw_w1.py, tests/data/w101_0.xml, tests/test_switching.py
When measure is 0.0, the `LecturaAportada` tag is not generated
=> FIX W1 Enables 0 as measure value

switching/input/messages/W1.py, switching/input/messages/__init__.py, tests/test_switching.py
* `contracte` as XML field
* W1 class import on input `__init__`
=> IMP W1 reading ERP compatible

.travis.yml
=> IMP Speedup travis tests

switching/output/messages/sw_c1.py, tests/data/CondContractuales.xml, tests/test_common.py
Add TipodeTelegestion in `CondicionesContractuales` model
=> New tipodetelegestion

switching/input/messages/C1.py
Adds TipodeTelegestion tag reading
=> NEW TipodeTelegestion reading

switching/input/messages/F1.py, tests/test_switching.py
`get_remesa` function to access RegistroFin registers
=> NEW get_remesa function and tests

switching/input/messages/message.py
=> IMP Shows XSD validation error

switching/output/messages/sw_r1.py
FIX typo error in ParametroContratacion Definition
=> FIX R1 typo in ParametroContratacion

switching/input/messages/C1.py
Do not fail when PM comentaries are present but empty , `<ComentariosPM></ComentariosPM>`
=> FIX PM Comentaries when empty

tests/data/c201_date_timezone.xml, tests/test_switching.py
NEW test for isodates in header
=> Fix fecha solicitud

switching/output/messages/sw_c1.py, tests/data/CondContractualesMedidaBaja.xml, tests/test_common.py
Creates branch `CondicionesContractuales` with 3.1A LB fields
=> IMP Contract conditions with 31lb fields creation

switching/__init__.py
=> Bump to v2.6.34

switching/input/messages/C1.py, switching/input/messages/M1.py, tests/data/c101_RegistroDoc.xml, tests/test_switching.py
Added:
- XML RegistrosDocumentos reading support
- Test for RegistrosDocumentos XML reading on C1 message
=> New RegistrosDocumento XML reading

.travis.yml
Remove python 2.6 test in travis
=> IMP remove python 2.6 travis test

switching/__init__.py
=> Bump to v2.6.36

switching/__init__.py
=> Bump to v2.6.37

switching/input/messages/TG.py
Add concentrator name to profile results. Necessary for supervising concentrators.
=> IMP Add CNC name to profile

switching/input/messages/message.py, tests/test_switching.py
Furthermore to allow importing an invalid XML we store the error result
=> Add possibilit to store the error of XSD validation

switching/__init__.py
=> Bump to v2.7.1

switching/input/messages/message.py
Change the API calls from Etree
=> Fix correct api usage from etree

switching/__init__.py
=> Bump to v2.8.1

switching/input/messages/F1.py, switching/input/messages/message.py, tests/test_switching.py
Added the necessary modifications in order to do the new import of F1.
=> New: Modifications for F1

switching/output/messages/sw_r1.py, tests/data/r101_minim_cups20.xml, tests/test_switching.py
Bad header on R1 steps on 20 chars header length CUPS
=> Fix fill cups r1

switching/helpers/funcions.py, switching/input/messages/defs.py, tests/test_common.py
Some of the datas in switching were missing the tariff 6.1B, which caused bugs.
=> Fixed missing 6.1B tariff in some defs

switching/defs.py
Closes https://github.com/gisce/erp/issues/4169
=> [FIX] Add blank option to ModoControlPotencia

switching/defs.py
Adds table with the codes of the distris who use option B of cut off in the process B1
=> Add table with distris who use option B in B1

switching/input/messages/F1.py, switching/input/messages/Q1.py, tests/test_switching.py
Added the following functions to F1:
=> New: More modifications for new F1

README.rst
This PR adds the badge ![](https://img.shields.io/pypi/v/switching.svg) to README
=> Update README to add PyPI version badge

switching/input/messages/F1.py, tests/test_switching.py
Added original date invoice to `get_create_invoice_params`
=> Added original date invoice
